# Generated by Django 3.0.1 on 2020-09-12 20:17

from django.db import migrations, models
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(editable=False, upload_to=timeline.models.user_uploads_directory_path, verbose_name='post image'),
        ),
    ]
