# Generated by Django 3.0.1 on 2020-09-12 21:05

from django.db import migrations, models
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20200912_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=timeline.models.user_uploads_directory_path, verbose_name='post image'),
        ),
    ]
