# Generated by Django 3.0.1 on 2020-08-10 03:11

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=profiles.models.default_profile_picture, upload_to=profiles.models.profile_directory_path, verbose_name='profile picture'),
        ),
    ]
