# Generated by Django 3.0.1 on 2020-08-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200813_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followed',
            new_name='following',
        ),
    ]
