# Generated by Django 3.0.1 on 2020-08-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', verbose_name='profile bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(default=[], related_name='_profile_followed_+', to='profiles.Profile'),
        ),
    ]
