# Generated by Django 3.0.1 on 2020-08-10 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20200809_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='profile bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='_profile_followed_+', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default=profiles.models.default_profile_picture, upload_to=profiles.models.profile_directory_path, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
